### PR TITLE
Added code formatting policy

### PR DESCRIPTION
**Pull request by pavzaj**
What do you think about consistent code formatting in solution? Codemaid can help.

### CODE REVIEW

**Comment by simondel** [comment]
I think consistent code formatting is very important. Is there a way that we can achieve it that will work for everyone? Not just people who happen to install CodeMaid? It would be great if the tool just worked without you having to do anything else.

**Comment by ptoonen** [comment]
Didn't know about CodeMaid. As I work in vscode a lot, it won't add much to my workflow, wouldn't a .editorconfig be an option?

**Comment by pavzaj** [comment]
@ptoonen you are right. I thought that editorconfig is also a plugin (http://editorconfig.org/#download), but in VS 2017 it is a built in feature (https://blogs.msdn.microsoft.com/dotnet/2016/12/15/code-style-configuration-in-the-vs2017-rc-update/). It seems to work somehow so let's try it out.

**Comment by ptoonen** [comment]
@pavzaj @richardwerkman has picked this up and we moved house to https://github.com/stryker-mutator/stryker-net Please find all the (new) code there if you're still interested in contributing. I'm closing this merge request now as we've made quite some strides since last year.

**Comment by pavzaj** [comment]
Thanks for info.

Pozdrawiam
Paweł Zając

**Pull request closed without merging**
