### PR TITLE
Test the MutatorOrchestrator

### PR DESCRIPTION
**Pull request by simondel**
We didn't have any tests for the MutatorOrchestrator so I added one. I'm aware that this code conflicts with the .NET core branch. I'll fix that after we merge either of the branches.

### CODE REVIEW

**Comment by simondel** [comment]
Note: This is PR is not yet done. I want to trigger SonarQube and refactor the code.

**Comment by ptoonen** [comment]
Might want to look into why it's triggering two builds too... branch + pr or is that because the push triggered one and then the subsequent pr did too?

**Comment by simondel** [comment]
I believe one builds this branch and one builds the branch after a merge with master. SonarQube only reports new issues right?

**Comment by simondel** [comment]
The branch `branch` build does:
```
git clone -q --branch=test-mutatororchestrator https://github.com/infosupport/stryker-net.git C:\projects\stryker-net
git checkout -qf ab0da2ce5bc7431fea300191ac7e410fb4997cb8
```
And the `pr` build does:
```
git clone -q https://github.com/infosupport/stryker-net.git C:\projects\stryker-net
git fetch -q origin +refs/pull/11/merge:
git checkout -qf FETCH_HEAD
```
So it seems to attempt to merge.

In other news. SonarQube ignores my unused variable :(

**Comment by pavzaj** [comment]
@simondel it seems to be a matter of build order. Sonarqube noticed your variable in some point of time, and then in has been removed in another point of time:
https://sonarqube.com/component_issues?id=Stryker.NET#types=CODE_SMELL|resolutions=FIXED

I think one build introduced this unused variable, and other removed it, so sonarqube marked it as "FIXED". I don't yet know wchich build done what . If there were only one build triggered it wouldn't happen.

**Comment by ptoonen** [comment]
@pavzaj how'd you configure it? Currently this repo is set to build on push and on PR. I kind of like it that way, but don't like how Sonar handles it :) Any ideas?

**Comment by pavzaj** [comment]
As I said, in my opinion two build definitions will solve the case. One should be configured to start on push and PR on master branch only and there should be SQ analysis. Second build definition configured on push (and PR maybe) on all branches other than master and it shouldn't start SQ analysis. It should only build and run tests. Alternatively on second branch we could run preview SQ analysis only.

Such configuration will give us every push built and tested, and every push and PR on master branch analysed in SQ.

**Comment by simondel** [comment]
Odd. SonarQube is acting up. Could it be because the Project GUID changed?
```
Sonarqube analysis for: 17f1fa339e0ec8d2ca796824ba07892b829b9ae2
Analysing Pull Request 11
SonarQube Scanner for MSBuild 2.2
The format of the analysis property sonar.login= is invalid
The format of the analysis property sonar.github.oauth= is invalid
Default properties file was found at C:\projects\stryker-net-u3136\Stryker.NET\packages\MSBuild.SonarQube.Runner.Tool.1.0.0\tools\SonarQube.Analysis.xml
Loading analysis properties from C:\projects\stryker-net-u3136\Stryker.NET\packages\MSBuild.SonarQube.Runner.Tool.1.0.0\tools\SonarQube.Analysis.xml
Command exited with code 1
```

**Comment by ptoonen** [comment]
@simondel my bad, forgot to save the changes :D

**Comment by ptoonen** [comment]
Fixed the issue with SonarQube analysis.

**Comment by pavzaj** [comment]
As I see this is the latest branch. When do you plan to merge with master?

**Comment by ptoonen** [comment]
@simondel any thoughts?

**Comment by simondel** [comment]
I'll make some changes tomorrow and then it can be merged

**Pull request merged**
