### PR TITLE
Port to dotnetcore

### PR DESCRIPTION
**Pull request by ptoonen**
Port from regular .NET to .NET core in order to provide xplat support.
Please don't mind the amount of commits - it's been a rough ride with only AppVeyor to build ;-)

### CODE REVIEW

**Comment by simondel** [comment]
How does this work with SonarQube? You expressed some concerns in issue #6

**Comment by ptoonen** [comment]
@simondel updated to include .NET core info. It works with SonarQube (see last comment on the issue):

- the sonar-msbuild-scanner looks for a ProjectGuid in the .csproj file - I have included placeholders there.
- it only works if the targets are in the right place. I have updated the InitializeSonarqubeAnalysis.bat file to copy the targets to the correct location.
- I have replaced OpenCover with DotCover so we can use it anyway.

**Comment by simondel** [comment]
Thanks for the hard work!

**Comment by pavzaj** [comment]
Agreed. You've done a lot:)

**Pull request merged**
